# Generated by Django 6.0.3 on 2026-03-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_alter_notes_uploaded_by'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
