# Generated by Django 6.0.3 on 2026-03-28 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_note_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='likes',
            new_name='liked_by',
        ),
    ]
